---
name: Classic FM - Saturday Night at the Movies
on:
  schedule:
    - cron: "55 18 * 1-3,11-12 6"
    - cron: "55 17 * 4-10 6"

jobs:
  record-classicfm:
    name: Record ClassicFM
    runs-on: ubuntu-20.04
    steps:
      - uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Radio Recorder
          token: ${{ secrets.PERSONAL_TOKEN }}
          inputs: '{ "id": "classicfm", "url": "http://media-ice.musicradio.com/ClassicFMMP3", "duration": "02:10:00" }'
