---
name: Classic FM - Saturday Night at the Movies
on:
  schedule:
    - cron: "50 18 * 1-3,11-12 6"
    - cron: "50 17 * 4-10 6"

jobs:
  record-classicfm:
    name: Record ClassicFM
    runs-on: ubuntu-22.04
    steps:
      - uses: ./.github/workflows/radio-recorder.yml
        with:
          id: "Classic FM"
          url: "http://media-ice.musicradio.com/ClassicFMMP3"
          duration: "02:10:00"
