---
name: Radio Recorder
on:
  workflow_call:
    inputs:
      id:
        description: "Name and ID for the stream"
        required: true
        type: string
      url:
        description: "Stream URL"
        required: true
        type: string
      duration:
        description: "Length of time to record: hh:mm:ss"
        required: true
        type: string
        default: "00:00:10"

jobs:
  record:
    name: Record a Stream
    runs-on: ubuntu-24.04
    steps:
      - name: Stream to file
        run: |
          docker run --rm \
            -v "$PWD":/data \
            ghcr.io/jrottenberg/ffmpeg:7.1-alpine \
            -i '${{ inputs.url }}' -t '${{ inputs.duration }}' -f mp3 /data/output.mp3
      - name: Add file to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.id }}
          path: output.mp3
