---
name: Radio Recorder
on:
  workflow_call:
    inputs:
      id:
        description: "Name and ID for the stream"
        required: true
        type: string
      url:
        description: "Stream URL"
        required: true
        type: string
      duration:
        description: "Length of time to record: hh:mm:ss"
        required: true
        type: string

jobs:
  record:
    name: Record a URL
    runs-on: ubuntu-24.04
    steps:
      - uses: FedericoCarboni/setup-ffmpeg@v3
        with:
          ffmpeg-version: 7.0.2
      - name: Steam to file
        run: ffmpeg -i '${{ inputs.url }}' -t '${{ inputs.duration }}' -f mp3 output.mp3
      - name: Add file to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.id }}
          path: output.mp3
