---
name: Radio Recorder
on:
  workflow_dispatch:
    inputs:
      id:
        description: 'Name and ID for the stream'
        required: true
      url:
        description: 'Stream URL'
        required: true
      duration:
        description: 'Length of time to record: hh:mm:ss'
        required: true

jobs:
  record:
    name: Record a URL
    runs-on: ubuntu-20.04
    steps:
      - name: Install ffmpeg
        run: sudo apt install -y ffmpeg
      - name: Run ffmpeg
        run: ffmpeg -i ${{ github.event.inputs.url }} -t ${{ github.event.inputs.duration }} -f mp3 output.mp3
      - name: Save file
        run: ls -lah output.mp3
      - name: Save output as artefact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.inputs.id }}
          path: output.mp3
