---
name: Radio Recorder
on:
  workflow_dispatch:
    inputs:
      id:
        description: 'Name and ID for the stream'
        required: true
      url:
        description: 'Stream URL'
        required: true
      duration:
        description: 'Length of time to record: hh:mm:ss'
        required: true

jobs:
  record:
    name: Record a URL
    runs-on: ubuntu-20.04
    steps:
      - name: Install ffmpeg
        run: sudo apt install -y ffmpeg
      - name: Get current date and time
        id: date
        run: echo "::set-output name=date::$(date --iso-8601=second)"
      - name: Run ffmpeg
        run: ffmpeg -i ${{ github.event.inputs.url }} -t ${{ github.event.inputs.duration }} -f mp3 output.mp3
      - name: Save file
        uses: yamatt/backblaze-b2-upload-action@v5
        with:
          key_id: ${{ secrets.B2_KEY_ID }}
          application_key: ${{ secrets.B2_APPLICATION_KEY }}
          bucket_name: ${{ secrets.B2_BUCKET_NAME }}
          file_path: output.mp3
          remote_path: ${{ github.event.inputs.id }}/${{ steps.date.outputs.date }}.mp3
