---
name: Test Radio Recorder
on:
  workflow_dispatch: {}

jobs:
  record-test:
    uses: "./.github/workflows/radio-recorder.yml"
    with:
      id: "BBC World Service - Test"
      url: "http://stream.live.vc.bbcmedia.co.uk/bbc_world_service"
      duration: "00:00:30"
