---
name: Test Radio Recorder
on:
  workflow_dispatch: {}

jobs:
  record-test:
    name: Test recording
    runs-on: ubuntu-20.04
    steps:
      - uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Radio Recorder
          token: ${{ secrets.PERSONAL_TOKEN }}
          inputs: '{ "id": "bbc-world-service", "url": "http://stream.live.vc.bbcmedia.co.uk/bbc_world_service", "duration": "00:00:30" }'
